title: Country.io .                                   <script async type="text/javascript">var REPO="country.io";</script><script async type="text/javascript" src="/incl.js"></script>
description: Country codes in JSON
