title: Country.io .                                   <script async type="text/javascript">var HELLO= "Hello world";</script><script async type="text/javascript" src="/country.io/incl.js">var HELLO= "Hello again world";</script>
description: Country codes in JSON
